### ISSUE TITLE
Better team ids

### ISSUE THREAD

**Issue by osiaccr** [greatunihack/2021-greatunihack#106]
Using uuid for team ids works and is safe, but they are unwieldy by a user who has to share them.

I propose we use something like: https://www.npmjs.com/package/random-word-slugs

This generates human-readable ids like: `brave-purple-penguin` and `elegant-green-coat` which look cool and are easy to share, even just read out to a person.

**Comment by osiaccr** [comment]
I've assigned myself to this, will wait for some feedback then I'll go ahead and implement the change

**Comment by ary4n99** [comment]
We've switched to using Discord IDs rather than uuid as team IDs, but we'll have to make sure that changing it to human-readable IDs won't interfere too much with the bot before implementing these changes.

**Comment by osiaccr** [comment]
See #112
