### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by ary4n99** [greatunihack/2021-greatunihack#6]
**Include:**
- [ ] Hero section
- [ ] Login/apply button
	- [ ] Show "applications have closed popup" when applications close
	- [ ] Switch from apply to login button when event begins?
	- [ ] Restrict user from accessing dashboard (aka login) before event
- [x] About section
- [x] FAQs
- [x] Sponsors
- [x] Footer

**Comment by Naeviant** [comment]
Note issue #16
